import "./Calculator.css"
import { useState } from "react";


const nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0];
const actions = ["/", "*", "+", "-", "="];


function Calculator() {
  const isClickedareAction = (act) => {
    return ["*", "/", "="].some((action) => action === act.toString());
  };
  const [value, setValue] = useState("");
  const [num, SetNum] = useState("");
  const handlenum = (val) => {
    if (!num.length && isClickedareAction(val)) {
      SetNum("");
      return;
    }
    if (val === "=") {
      console.log(num);

      let a = new Function("return " + num)();
      setValue(a.toString());

      let b = a.toString();
      console.log(b);
      SetNum(num + b);
    }
    SetNum(num + val);
  };
  const clearall = () => {
    SetNum("");
    setValue("");
  };
  return (
    <section>
    <h1>Calculator App</h1>
    <div className="Calc">
      <div className="a-area">
        <div className="area">
          {num}
          {value.length > 3 ? value.slice(0, 5) : value}
        </div>
        <div className="actions">
          {actions.map((action, index) => (
            <span id="act" onClick={() => handlenum(action)}>{action}</span>
          ))}
        </div>
        <div className="numbers">
          {nums.map((num, index) => (
            <span onClick={() => handlenum(num)}>{num}</span>
          ))}
          <span id="Cc" onClick={clearall}>C</span>
        </div>
      </div>
      <strong>Image Generated by <a target="_black" href="https://gemini.google.com/app">Gemini</a></strong>
    </div>
    </section>
  );
}
export default Calculator;